#define ENABLE_RB0_PULLUP() _CN2PUE = 1
#define DISABLE_RB0_PULLUP() _CN2PUE = 0
#define ENABLE_RB1_PULLUP() _CN3PUE = 1
#define DISABLE_RB1_PULLUP() _CN3PUE = 0
#define ENABLE_RB2_PULLUP() _CN4PUE = 1
#define DISABLE_RB2_PULLUP() _CN4PUE = 0
#define ENABLE_RB3_PULLUP() _CN5PUE = 1
#define DISABLE_RB3_PULLUP() _CN5PUE = 0
#define ENABLE_RB4_PULLUP() _CN6PUE = 1
#define DISABLE_RB4_PULLUP() _CN6PUE = 0
#define ENABLE_RB5_PULLUP() _CN7PUE = 1
#define DISABLE_RB5_PULLUP() _CN7PUE = 0
#define ENABLE_RB6_PULLUP() _CN24PUE = 1
#define DISABLE_RB6_PULLUP() _CN24PUE = 0
#define ENABLE_RB7_PULLUP() _CN25PUE = 1
#define DISABLE_RB7_PULLUP() _CN25PUE = 0
#define ENABLE_RB8_PULLUP() _CN26PUE = 1
#define DISABLE_RB8_PULLUP() _CN26PUE = 0
#define ENABLE_RB9_PULLUP() _CN27PUE = 1
#define DISABLE_RB9_PULLUP() _CN27PUE = 0
#define ENABLE_RB10_PULLUP() _CN28PUE = 1
#define DISABLE_RB10_PULLUP() _CN28PUE = 0
#define ENABLE_RB11_PULLUP() _CN29PUE = 1
#define DISABLE_RB11_PULLUP() _CN29PUE = 0
#define ENABLE_RB12_PULLUP() _CN30PUE = 1
#define DISABLE_RB12_PULLUP() _CN30PUE = 0
#define ENABLE_RB13_PULLUP() _CN31PUE = 1
#define DISABLE_RB13_PULLUP() _CN31PUE = 0
#define ENABLE_RB14_PULLUP() _CN32PUE = 1
#define DISABLE_RB14_PULLUP() _CN32PUE = 0
#define ENABLE_RB15_PULLUP() _CN12PUE = 1
#define DISABLE_RB15_PULLUP() _CN12PUE = 0
#define ENABLE_RC12_PULLUP() _CN23PUE = 1
#define DISABLE_RC12_PULLUP() _CN23PUE = 0
#define ENABLE_RC13_PULLUP() _CN1PUE = 1
#define DISABLE_RC13_PULLUP() _CN1PUE = 0
#define ENABLE_RC14_PULLUP() _CN0PUE = 1
#define DISABLE_RC14_PULLUP() _CN0PUE = 0
#define ENABLE_RC15_PULLUP() _CN22PUE = 1
#define DISABLE_RC15_PULLUP() _CN22PUE = 0
#define ENABLE_RD0_PULLUP() _CN49PUE = 1
#define DISABLE_RD0_PULLUP() _CN49PUE = 0
#define ENABLE_RD1_PULLUP() _CN50PUE = 1
#define DISABLE_RD1_PULLUP() _CN50PUE = 0
#define ENABLE_RD2_PULLUP() _CN51PUE = 1
#define DISABLE_RD2_PULLUP() _CN51PUE = 0
#define ENABLE_RD3_PULLUP() _CN52PUE = 1
#define DISABLE_RD3_PULLUP() _CN52PUE = 0
#define ENABLE_RD4_PULLUP() _CN13PUE = 1
#define DISABLE_RD4_PULLUP() _CN13PUE = 0
#define ENABLE_RD5_PULLUP() _CN14PUE = 1
#define DISABLE_RD5_PULLUP() _CN14PUE = 0
#define ENABLE_RD6_PULLUP() _CN15PUE = 1
#define DISABLE_RD6_PULLUP() _CN15PUE = 0
#define ENABLE_RD7_PULLUP() _CN16PUE = 1
#define DISABLE_RD7_PULLUP() _CN16PUE = 0
#define ENABLE_RD8_PULLUP() _CN53PUE = 1
#define DISABLE_RD8_PULLUP() _CN53PUE = 0
#define ENABLE_RD9_PULLUP() _CN54PUE = 1
#define DISABLE_RD9_PULLUP() _CN54PUE = 0
#define ENABLE_RD10_PULLUP() _CN55PUE = 1
#define DISABLE_RD10_PULLUP() _CN55PUE = 0
#define ENABLE_RD11_PULLUP() _CN56PUE = 1
#define DISABLE_RD11_PULLUP() _CN56PUE = 0
#define ENABLE_RE0_PULLUP() _CN58PUE = 1
#define DISABLE_RE0_PULLUP() _CN58PUE = 0
#define ENABLE_RE1_PULLUP() _CN59PUE = 1
#define DISABLE_RE1_PULLUP() _CN59PUE = 0
#define ENABLE_RE2_PULLUP() _CN60PUE = 1
#define DISABLE_RE2_PULLUP() _CN60PUE = 0
#define ENABLE_RE3_PULLUP() _CN61PUE = 1
#define DISABLE_RE3_PULLUP() _CN61PUE = 0
#define ENABLE_RE4_PULLUP() _CN62PUE = 1
#define DISABLE_RE4_PULLUP() _CN62PUE = 0
#define ENABLE_RE5_PULLUP() _CN63PUE = 1
#define DISABLE_RE5_PULLUP() _CN63PUE = 0
#define ENABLE_RE6_PULLUP() _CN64PUE = 1
#define DISABLE_RE6_PULLUP() _CN64PUE = 0
#define ENABLE_RE7_PULLUP() _CN65PUE = 1
#define DISABLE_RE7_PULLUP() _CN65PUE = 0
#define ENABLE_RF0_PULLUP() _CN68PUE = 1
#define DISABLE_RF0_PULLUP() _CN68PUE = 0
#define ENABLE_RF1_PULLUP() _CN69PUE = 1
#define DISABLE_RF1_PULLUP() _CN69PUE = 0
#define ENABLE_RF2_PULLUP() _CN70PUE = 1
#define DISABLE_RF2_PULLUP() _CN70PUE = 0
#define ENABLE_RF3_PULLUP() _CN71PUE = 1
#define DISABLE_RF3_PULLUP() _CN71PUE = 0
#define ENABLE_RF4_PULLUP() _CN17PUE = 1
#define DISABLE_RF4_PULLUP() _CN17PUE = 0
#define ENABLE_RF5_PULLUP() _CN18PUE = 1
#define DISABLE_RF5_PULLUP() _CN18PUE = 0
#define ENABLE_RF6_PULLUP() _CN72PUE = 1
#define DISABLE_RF6_PULLUP() _CN72PUE = 0
#define ENABLE_RG2_PULLUP() _CN83PUE = 1
#define DISABLE_RG2_PULLUP() _CN83PUE = 0
#define ENABLE_RG3_PULLUP() _CN84PUE = 1
#define DISABLE_RG3_PULLUP() _CN84PUE = 0
#define ENABLE_RG6_PULLUP() _CN8PUE = 1
#define DISABLE_RG6_PULLUP() _CN8PUE = 0
#define ENABLE_RG7_PULLUP() _CN9PUE = 1
#define DISABLE_RG7_PULLUP() _CN9PUE = 0
#define ENABLE_RG8_PULLUP() _CN10PUE = 1
#define DISABLE_RG8_PULLUP() _CN10PUE = 0
#define ENABLE_RG9_PULLUP() _CN11PUE = 1
#define DISABLE_RG9_PULLUP() _CN11PUE = 0
#define ENABLE_RB0_CN_INTERRUPT() _CN2IE = 1
#define DISABLE_RB0_CN_INTERRUPT() _CN2IE = 0
#define ENABLE_RB1_CN_INTERRUPT() _CN3IE = 1
#define DISABLE_RB1_CN_INTERRUPT() _CN3IE = 0
#define ENABLE_RB2_CN_INTERRUPT() _CN4IE = 1
#define DISABLE_RB2_CN_INTERRUPT() _CN4IE = 0
#define ENABLE_RB3_CN_INTERRUPT() _CN5IE = 1
#define DISABLE_RB3_CN_INTERRUPT() _CN5IE = 0
#define ENABLE_RB4_CN_INTERRUPT() _CN6IE = 1
#define DISABLE_RB4_CN_INTERRUPT() _CN6IE = 0
#define ENABLE_RB5_CN_INTERRUPT() _CN7IE = 1
#define DISABLE_RB5_CN_INTERRUPT() _CN7IE = 0
#define ENABLE_RB6_CN_INTERRUPT() _CN24IE = 1
#define DISABLE_RB6_CN_INTERRUPT() _CN24IE = 0
#define ENABLE_RB7_CN_INTERRUPT() _CN25IE = 1
#define DISABLE_RB7_CN_INTERRUPT() _CN25IE = 0
#define ENABLE_RB8_CN_INTERRUPT() _CN26IE = 1
#define DISABLE_RB8_CN_INTERRUPT() _CN26IE = 0
#define ENABLE_RB9_CN_INTERRUPT() _CN27IE = 1
#define DISABLE_RB9_CN_INTERRUPT() _CN27IE = 0
#define ENABLE_RB10_CN_INTERRUPT() _CN28IE = 1
#define DISABLE_RB10_CN_INTERRUPT() _CN28IE = 0
#define ENABLE_RB11_CN_INTERRUPT() _CN29IE = 1
#define DISABLE_RB11_CN_INTERRUPT() _CN29IE = 0
#define ENABLE_RB12_CN_INTERRUPT() _CN30IE = 1
#define DISABLE_RB12_CN_INTERRUPT() _CN30IE = 0
#define ENABLE_RB13_CN_INTERRUPT() _CN31IE = 1
#define DISABLE_RB13_CN_INTERRUPT() _CN31IE = 0
#define ENABLE_RB14_CN_INTERRUPT() _CN32IE = 1
#define DISABLE_RB14_CN_INTERRUPT() _CN32IE = 0
#define ENABLE_RB15_CN_INTERRUPT() _CN12IE = 1
#define DISABLE_RB15_CN_INTERRUPT() _CN12IE = 0
#define ENABLE_RC12_CN_INTERRUPT() _CN23IE = 1
#define DISABLE_RC12_CN_INTERRUPT() _CN23IE = 0
#define ENABLE_RC13_CN_INTERRUPT() _CN1IE = 1
#define DISABLE_RC13_CN_INTERRUPT() _CN1IE = 0
#define ENABLE_RC14_CN_INTERRUPT() _CN0IE = 1
#define DISABLE_RC14_CN_INTERRUPT() _CN0IE = 0
#define ENABLE_RC15_CN_INTERRUPT() _CN22IE = 1
#define DISABLE_RC15_CN_INTERRUPT() _CN22IE = 0
#define ENABLE_RD0_CN_INTERRUPT() _CN49IE = 1
#define DISABLE_RD0_CN_INTERRUPT() _CN49IE = 0
#define ENABLE_RD1_CN_INTERRUPT() _CN50IE = 1
#define DISABLE_RD1_CN_INTERRUPT() _CN50IE = 0
#define ENABLE_RD2_CN_INTERRUPT() _CN51IE = 1
#define DISABLE_RD2_CN_INTERRUPT() _CN51IE = 0
#define ENABLE_RD3_CN_INTERRUPT() _CN52IE = 1
#define DISABLE_RD3_CN_INTERRUPT() _CN52IE = 0
#define ENABLE_RD4_CN_INTERRUPT() _CN13IE = 1
#define DISABLE_RD4_CN_INTERRUPT() _CN13IE = 0
#define ENABLE_RD5_CN_INTERRUPT() _CN14IE = 1
#define DISABLE_RD5_CN_INTERRUPT() _CN14IE = 0
#define ENABLE_RD6_CN_INTERRUPT() _CN15IE = 1
#define DISABLE_RD6_CN_INTERRUPT() _CN15IE = 0
#define ENABLE_RD7_CN_INTERRUPT() _CN16IE = 1
#define DISABLE_RD7_CN_INTERRUPT() _CN16IE = 0
#define ENABLE_RD8_CN_INTERRUPT() _CN53IE = 1
#define DISABLE_RD8_CN_INTERRUPT() _CN53IE = 0
#define ENABLE_RD9_CN_INTERRUPT() _CN54IE = 1
#define DISABLE_RD9_CN_INTERRUPT() _CN54IE = 0
#define ENABLE_RD10_CN_INTERRUPT() _CN55IE = 1
#define DISABLE_RD10_CN_INTERRUPT() _CN55IE = 0
#define ENABLE_RD11_CN_INTERRUPT() _CN56IE = 1
#define DISABLE_RD11_CN_INTERRUPT() _CN56IE = 0
#define ENABLE_RE0_CN_INTERRUPT() _CN58IE = 1
#define DISABLE_RE0_CN_INTERRUPT() _CN58IE = 0
#define ENABLE_RE1_CN_INTERRUPT() _CN59IE = 1
#define DISABLE_RE1_CN_INTERRUPT() _CN59IE = 0
#define ENABLE_RE2_CN_INTERRUPT() _CN60IE = 1
#define DISABLE_RE2_CN_INTERRUPT() _CN60IE = 0
#define ENABLE_RE3_CN_INTERRUPT() _CN61IE = 1
#define DISABLE_RE3_CN_INTERRUPT() _CN61IE = 0
#define ENABLE_RE4_CN_INTERRUPT() _CN62IE = 1
#define DISABLE_RE4_CN_INTERRUPT() _CN62IE = 0
#define ENABLE_RE5_CN_INTERRUPT() _CN63IE = 1
#define DISABLE_RE5_CN_INTERRUPT() _CN63IE = 0
#define ENABLE_RE6_CN_INTERRUPT() _CN64IE = 1
#define DISABLE_RE6_CN_INTERRUPT() _CN64IE = 0
#define ENABLE_RE7_CN_INTERRUPT() _CN65IE = 1
#define DISABLE_RE7_CN_INTERRUPT() _CN65IE = 0
#define ENABLE_RF0_CN_INTERRUPT() _CN68IE = 1
#define DISABLE_RF0_CN_INTERRUPT() _CN68IE = 0
#define ENABLE_RF1_CN_INTERRUPT() _CN69IE = 1
#define DISABLE_RF1_CN_INTERRUPT() _CN69IE = 0
#define ENABLE_RF2_CN_INTERRUPT() _CN70IE = 1
#define DISABLE_RF2_CN_INTERRUPT() _CN70IE = 0
#define ENABLE_RF3_CN_INTERRUPT() _CN71IE = 1
#define DISABLE_RF3_CN_INTERRUPT() _CN71IE = 0
#define ENABLE_RF4_CN_INTERRUPT() _CN17IE = 1
#define DISABLE_RF4_CN_INTERRUPT() _CN17IE = 0
#define ENABLE_RF5_CN_INTERRUPT() _CN18IE = 1
#define DISABLE_RF5_CN_INTERRUPT() _CN18IE = 0
#define ENABLE_RF6_CN_INTERRUPT() _CN72IE = 1
#define DISABLE_RF6_CN_INTERRUPT() _CN72IE = 0
#define ENABLE_RG2_CN_INTERRUPT() _CN83IE = 1
#define DISABLE_RG2_CN_INTERRUPT() _CN83IE = 0
#define ENABLE_RG3_CN_INTERRUPT() _CN84IE = 1
#define DISABLE_RG3_CN_INTERRUPT() _CN84IE = 0
#define ENABLE_RG6_CN_INTERRUPT() _CN8IE = 1
#define DISABLE_RG6_CN_INTERRUPT() _CN8IE = 0
#define ENABLE_RG7_CN_INTERRUPT() _CN9IE = 1
#define DISABLE_RG7_CN_INTERRUPT() _CN9IE = 0
#define ENABLE_RG8_CN_INTERRUPT() _CN10IE = 1
#define DISABLE_RG8_CN_INTERRUPT() _CN10IE = 0
#define ENABLE_RG9_CN_INTERRUPT() _CN11IE = 1
#define DISABLE_RG9_CN_INTERRUPT() _CN11IE = 0
#define DISABLE_RB0_ANALOG() _PCFG0 = 1
#define ENABLE_RB0_ANALOG() _PCFG0 = 0
#define DISABLE_RB1_ANALOG() _PCFG1 = 1
#define ENABLE_RB1_ANALOG() _PCFG1 = 0
#define DISABLE_RB2_ANALOG() _PCFG2 = 1
#define ENABLE_RB2_ANALOG() _PCFG2 = 0
#define DISABLE_RB3_ANALOG() _PCFG3 = 1
#define ENABLE_RB3_ANALOG() _PCFG3 = 0
#define DISABLE_RB4_ANALOG() _PCFG4 = 1
#define ENABLE_RB4_ANALOG() _PCFG4 = 0
#define DISABLE_RB5_ANALOG() _PCFG5 = 1
#define ENABLE_RB5_ANALOG() _PCFG5 = 0
#define DISABLE_RB6_ANALOG() _PCFG6 = 1
#define ENABLE_RB6_ANALOG() _PCFG6 = 0
#define DISABLE_RB7_ANALOG() _PCFG7 = 1
#define ENABLE_RB7_ANALOG() _PCFG7 = 0
#define DISABLE_RB8_ANALOG() _PCFG8 = 1
#define ENABLE_RB8_ANALOG() _PCFG8 = 0
#define DISABLE_RB9_ANALOG() _PCFG9 = 1
#define ENABLE_RB9_ANALOG() _PCFG9 = 0
#define DISABLE_RB10_ANALOG() _PCFG10 = 1
#define ENABLE_RB10_ANALOG() _PCFG10 = 0
#define DISABLE_RB11_ANALOG() _PCFG11 = 1
#define ENABLE_RB11_ANALOG() _PCFG11 = 0
#define DISABLE_RB12_ANALOG() _PCFG12 = 1
#define ENABLE_RB12_ANALOG() _PCFG12 = 0
#define DISABLE_RB13_ANALOG() _PCFG13 = 1
#define ENABLE_RB13_ANALOG() _PCFG13 = 0
#define DISABLE_RB14_ANALOG() _PCFG14 = 1
#define ENABLE_RB14_ANALOG() _PCFG14 = 0
#define DISABLE_RB15_ANALOG() _PCFG15 = 1
#define ENABLE_RB15_ANALOG() _PCFG15 = 0
#define ENABLE_RB0_OPENDRAIN() _ODB0 = 1
#define DISABLE_RB0_OPENDRAIN() _ODB0 = 0
#define ENABLE_RB1_OPENDRAIN() _ODB1 = 1
#define DISABLE_RB1_OPENDRAIN() _ODB1 = 0
#define ENABLE_RB2_OPENDRAIN() _ODB2 = 1
#define DISABLE_RB2_OPENDRAIN() _ODB2 = 0
#define ENABLE_RB3_OPENDRAIN() _ODB3 = 1
#define DISABLE_RB3_OPENDRAIN() _ODB3 = 0
#define ENABLE_RB4_OPENDRAIN() _ODB4 = 1
#define DISABLE_RB4_OPENDRAIN() _ODB4 = 0
#define ENABLE_RB5_OPENDRAIN() _ODB5 = 1
#define DISABLE_RB5_OPENDRAIN() _ODB5 = 0
#define ENABLE_RB6_OPENDRAIN() _ODB6 = 1
#define DISABLE_RB6_OPENDRAIN() _ODB6 = 0
#define ENABLE_RB7_OPENDRAIN() _ODB7 = 1
#define DISABLE_RB7_OPENDRAIN() _ODB7 = 0
#define ENABLE_RB8_OPENDRAIN() _ODB8 = 1
#define DISABLE_RB8_OPENDRAIN() _ODB8 = 0
#define ENABLE_RB9_OPENDRAIN() _ODB9 = 1
#define DISABLE_RB9_OPENDRAIN() _ODB9 = 0
#define ENABLE_RB10_OPENDRAIN() _ODB10 = 1
#define DISABLE_RB10_OPENDRAIN() _ODB10 = 0
#define ENABLE_RB11_OPENDRAIN() _ODB11 = 1
#define DISABLE_RB11_OPENDRAIN() _ODB11 = 0
#define ENABLE_RB12_OPENDRAIN() _ODB12 = 1
#define DISABLE_RB12_OPENDRAIN() _ODB12 = 0
#define ENABLE_RB13_OPENDRAIN() _ODB13 = 1
#define DISABLE_RB13_OPENDRAIN() _ODB13 = 0
#define ENABLE_RB14_OPENDRAIN() _ODB14 = 1
#define DISABLE_RB14_OPENDRAIN() _ODB14 = 0
#define ENABLE_RB15_OPENDRAIN() _ODB15 = 1
#define DISABLE_RB15_OPENDRAIN() _ODB15 = 0
#define ENABLE_RC12_OPENDRAIN() _ODC12 = 1
#define DISABLE_RC12_OPENDRAIN() _ODC12 = 0
#define ENABLE_RC13_OPENDRAIN() _ODC13 = 1
#define DISABLE_RC13_OPENDRAIN() _ODC13 = 0
#define ENABLE_RC14_OPENDRAIN() _ODC14 = 1
#define DISABLE_RC14_OPENDRAIN() _ODC14 = 0
#define ENABLE_RC15_OPENDRAIN() _ODC15 = 1
#define DISABLE_RC15_OPENDRAIN() _ODC15 = 0
#define ENABLE_RD0_OPENDRAIN() _ODD0 = 1
#define DISABLE_RD0_OPENDRAIN() _ODD0 = 0
#define ENABLE_RD1_OPENDRAIN() _ODD1 = 1
#define DISABLE_RD1_OPENDRAIN() _ODD1 = 0
#define ENABLE_RD2_OPENDRAIN() _ODD2 = 1
#define DISABLE_RD2_OPENDRAIN() _ODD2 = 0
#define ENABLE_RD3_OPENDRAIN() _ODD3 = 1
#define DISABLE_RD3_OPENDRAIN() _ODD3 = 0
#define ENABLE_RD4_OPENDRAIN() _ODD4 = 1
#define DISABLE_RD4_OPENDRAIN() _ODD4 = 0
#define ENABLE_RD5_OPENDRAIN() _ODD5 = 1
#define DISABLE_RD5_OPENDRAIN() _ODD5 = 0
#define ENABLE_RD6_OPENDRAIN() _ODD6 = 1
#define DISABLE_RD6_OPENDRAIN() _ODD6 = 0
#define ENABLE_RD7_OPENDRAIN() _ODD7 = 1
#define DISABLE_RD7_OPENDRAIN() _ODD7 = 0
#define ENABLE_RD8_OPENDRAIN() _ODD8 = 1
#define DISABLE_RD8_OPENDRAIN() _ODD8 = 0
#define ENABLE_RD9_OPENDRAIN() _ODD9 = 1
#define DISABLE_RD9_OPENDRAIN() _ODD9 = 0
#define ENABLE_RD10_OPENDRAIN() _ODD10 = 1
#define DISABLE_RD10_OPENDRAIN() _ODD10 = 0
#define ENABLE_RD11_OPENDRAIN() _ODD11 = 1
#define DISABLE_RD11_OPENDRAIN() _ODD11 = 0
#define ENABLE_RE0_OPENDRAIN() _ODE0 = 1
#define DISABLE_RE0_OPENDRAIN() _ODE0 = 0
#define ENABLE_RE1_OPENDRAIN() _ODE1 = 1
#define DISABLE_RE1_OPENDRAIN() _ODE1 = 0
#define ENABLE_RE2_OPENDRAIN() _ODE2 = 1
#define DISABLE_RE2_OPENDRAIN() _ODE2 = 0
#define ENABLE_RE3_OPENDRAIN() _ODE3 = 1
#define DISABLE_RE3_OPENDRAIN() _ODE3 = 0
#define ENABLE_RE4_OPENDRAIN() _ODE4 = 1
#define DISABLE_RE4_OPENDRAIN() _ODE4 = 0
#define ENABLE_RE5_OPENDRAIN() _ODE5 = 1
#define DISABLE_RE5_OPENDRAIN() _ODE5 = 0
#define ENABLE_RE6_OPENDRAIN() _ODE6 = 1
#define DISABLE_RE6_OPENDRAIN() _ODE6 = 0
#define ENABLE_RE7_OPENDRAIN() _ODE7 = 1
#define DISABLE_RE7_OPENDRAIN() _ODE7 = 0
#define ENABLE_RF0_OPENDRAIN() _ODF0 = 1
#define DISABLE_RF0_OPENDRAIN() _ODF0 = 0
#define ENABLE_RF1_OPENDRAIN() _ODF1 = 1
#define DISABLE_RF1_OPENDRAIN() _ODF1 = 0
#define ENABLE_RF2_OPENDRAIN() _ODF2 = 1
#define DISABLE_RF2_OPENDRAIN() _ODF2 = 0
#define ENABLE_RF3_OPENDRAIN() _ODF3 = 1
#define DISABLE_RF3_OPENDRAIN() _ODF3 = 0
#define ENABLE_RF4_OPENDRAIN() _ODF4 = 1
#define DISABLE_RF4_OPENDRAIN() _ODF4 = 0
#define ENABLE_RF5_OPENDRAIN() _ODF5 = 1
#define DISABLE_RF5_OPENDRAIN() _ODF5 = 0
#define ENABLE_RF6_OPENDRAIN() _ODF6 = 1
#define DISABLE_RF6_OPENDRAIN() _ODF6 = 0
#define ENABLE_RG2_OPENDRAIN() _ODG2 = 1
#define DISABLE_RG2_OPENDRAIN() _ODG2 = 0
#define ENABLE_RG3_OPENDRAIN() _ODG3 = 1
#define DISABLE_RG3_OPENDRAIN() _ODG3 = 0
#define ENABLE_RG6_OPENDRAIN() _ODG6 = 1
#define DISABLE_RG6_OPENDRAIN() _ODG6 = 0
#define ENABLE_RG7_OPENDRAIN() _ODG7 = 1
#define DISABLE_RG7_OPENDRAIN() _ODG7 = 0
#define ENABLE_RG8_OPENDRAIN() _ODG8 = 1
#define DISABLE_RG8_OPENDRAIN() _ODG8 = 0
#define ENABLE_RG9_OPENDRAIN() _ODG9 = 1
#define DISABLE_RG9_OPENDRAIN() _ODG9 = 0
static inline void CONFIG_RB0_AS_DIG_OUTPUT(){
 DISABLE_RB0_PULLUP();
 DISABLE_RB0_OPENDRAIN();
 _TRISB0 = 0;
 _PCFG0 = 1;
}
static inline void CONFIG_RB1_AS_DIG_OUTPUT(){
 DISABLE_RB1_PULLUP();
 DISABLE_RB1_OPENDRAIN();
 _TRISB1 = 0;
 _PCFG1 = 1;
}
static inline void CONFIG_RB2_AS_DIG_OUTPUT(){
 DISABLE_RB2_PULLUP();
 DISABLE_RB2_OPENDRAIN();
 _TRISB2 = 0;
 _PCFG2 = 1;
}
static inline void CONFIG_RB3_AS_DIG_OUTPUT(){
 DISABLE_RB3_PULLUP();
 DISABLE_RB3_OPENDRAIN();
 _TRISB3 = 0;
 _PCFG3 = 1;
}
static inline void CONFIG_RB4_AS_DIG_OUTPUT(){
 DISABLE_RB4_PULLUP();
 DISABLE_RB4_OPENDRAIN();
 _TRISB4 = 0;
 _PCFG4 = 1;
}
static inline void CONFIG_RB5_AS_DIG_OUTPUT(){
 DISABLE_RB5_PULLUP();
 DISABLE_RB5_OPENDRAIN();
 _TRISB5 = 0;
 _PCFG5 = 1;
}
static inline void CONFIG_RB6_AS_DIG_OUTPUT(){
 DISABLE_RB6_PULLUP();
 DISABLE_RB6_OPENDRAIN();
 _TRISB6 = 0;
 _PCFG6 = 1;
}
static inline void CONFIG_RB7_AS_DIG_OUTPUT(){
 DISABLE_RB7_PULLUP();
 DISABLE_RB7_OPENDRAIN();
 _TRISB7 = 0;
 _PCFG7 = 1;
}
static inline void CONFIG_RB8_AS_DIG_OUTPUT(){
 DISABLE_RB8_PULLUP();
 DISABLE_RB8_OPENDRAIN();
 _TRISB8 = 0;
 _PCFG8 = 1;
}
static inline void CONFIG_RB9_AS_DIG_OUTPUT(){
 DISABLE_RB9_PULLUP();
 DISABLE_RB9_OPENDRAIN();
 _TRISB9 = 0;
 _PCFG9 = 1;
}
static inline void CONFIG_RB10_AS_DIG_OUTPUT(){
 DISABLE_RB10_PULLUP();
 DISABLE_RB10_OPENDRAIN();
 _TRISB10 = 0;
 _PCFG10 = 1;
}
static inline void CONFIG_RB11_AS_DIG_OUTPUT(){
 DISABLE_RB11_PULLUP();
 DISABLE_RB11_OPENDRAIN();
 _TRISB11 = 0;
 _PCFG11 = 1;
}
static inline void CONFIG_RB12_AS_DIG_OUTPUT(){
 DISABLE_RB12_PULLUP();
 DISABLE_RB12_OPENDRAIN();
 _TRISB12 = 0;
 _PCFG12 = 1;
}
static inline void CONFIG_RB13_AS_DIG_OUTPUT(){
 DISABLE_RB13_PULLUP();
 DISABLE_RB13_OPENDRAIN();
 _TRISB13 = 0;
 _PCFG13 = 1;
}
static inline void CONFIG_RB14_AS_DIG_OUTPUT(){
 DISABLE_RB14_PULLUP();
 DISABLE_RB14_OPENDRAIN();
 _TRISB14 = 0;
 _PCFG14 = 1;
}
static inline void CONFIG_RB15_AS_DIG_OUTPUT(){
 DISABLE_RB15_PULLUP();
 DISABLE_RB15_OPENDRAIN();
 _TRISB15 = 0;
 _PCFG15 = 1;
}
static inline void CONFIG_RC12_AS_DIG_OUTPUT(){
 DISABLE_RC12_PULLUP();
 DISABLE_RC12_OPENDRAIN();
 _TRISC12 = 0;
}
static inline void CONFIG_RC13_AS_DIG_OUTPUT(){
 DISABLE_RC13_PULLUP();
 DISABLE_RC13_OPENDRAIN();
 _TRISC13 = 0;
}
static inline void CONFIG_RC14_AS_DIG_OUTPUT(){
 DISABLE_RC14_PULLUP();
 DISABLE_RC14_OPENDRAIN();
 _TRISC14 = 0;
}
static inline void CONFIG_RC15_AS_DIG_OUTPUT(){
 DISABLE_RC15_PULLUP();
 DISABLE_RC15_OPENDRAIN();
 _TRISC15 = 0;
}
static inline void CONFIG_RD0_AS_DIG_OUTPUT(){
 DISABLE_RD0_PULLUP();
 DISABLE_RD0_OPENDRAIN();
 _TRISD0 = 0;
}
static inline void CONFIG_RD1_AS_DIG_OUTPUT(){
 DISABLE_RD1_PULLUP();
 DISABLE_RD1_OPENDRAIN();
 _TRISD1 = 0;
}
static inline void CONFIG_RD2_AS_DIG_OUTPUT(){
 DISABLE_RD2_PULLUP();
 DISABLE_RD2_OPENDRAIN();
 _TRISD2 = 0;
}
static inline void CONFIG_RD3_AS_DIG_OUTPUT(){
 DISABLE_RD3_PULLUP();
 DISABLE_RD3_OPENDRAIN();
 _TRISD3 = 0;
}
static inline void CONFIG_RD4_AS_DIG_OUTPUT(){
 DISABLE_RD4_PULLUP();
 DISABLE_RD4_OPENDRAIN();
 _TRISD4 = 0;
}
static inline void CONFIG_RD5_AS_DIG_OUTPUT(){
 DISABLE_RD5_PULLUP();
 DISABLE_RD5_OPENDRAIN();
 _TRISD5 = 0;
}
static inline void CONFIG_RD6_AS_DIG_OUTPUT(){
 DISABLE_RD6_PULLUP();
 DISABLE_RD6_OPENDRAIN();
 _TRISD6 = 0;
}
static inline void CONFIG_RD7_AS_DIG_OUTPUT(){
 DISABLE_RD7_PULLUP();
 DISABLE_RD7_OPENDRAIN();
 _TRISD7 = 0;
}
static inline void CONFIG_RD8_AS_DIG_OUTPUT(){
 DISABLE_RD8_PULLUP();
 DISABLE_RD8_OPENDRAIN();
 _TRISD8 = 0;
}
static inline void CONFIG_RD9_AS_DIG_OUTPUT(){
 DISABLE_RD9_PULLUP();
 DISABLE_RD9_OPENDRAIN();
 _TRISD9 = 0;
}
static inline void CONFIG_RD10_AS_DIG_OUTPUT(){
 DISABLE_RD10_PULLUP();
 DISABLE_RD10_OPENDRAIN();
 _TRISD10 = 0;
}
static inline void CONFIG_RD11_AS_DIG_OUTPUT(){
 DISABLE_RD11_PULLUP();
 DISABLE_RD11_OPENDRAIN();
 _TRISD11 = 0;
}
static inline void CONFIG_RE0_AS_DIG_OUTPUT(){
 DISABLE_RE0_PULLUP();
 DISABLE_RE0_OPENDRAIN();
 _TRISE0 = 0;
}
static inline void CONFIG_RE1_AS_DIG_OUTPUT(){
 DISABLE_RE1_PULLUP();
 DISABLE_RE1_OPENDRAIN();
 _TRISE1 = 0;
}
static inline void CONFIG_RE2_AS_DIG_OUTPUT(){
 DISABLE_RE2_PULLUP();
 DISABLE_RE2_OPENDRAIN();
 _TRISE2 = 0;
}
static inline void CONFIG_RE3_AS_DIG_OUTPUT(){
 DISABLE_RE3_PULLUP();
 DISABLE_RE3_OPENDRAIN();
 _TRISE3 = 0;
}
static inline void CONFIG_RE4_AS_DIG_OUTPUT(){
 DISABLE_RE4_PULLUP();
 DISABLE_RE4_OPENDRAIN();
 _TRISE4 = 0;
}
static inline void CONFIG_RE5_AS_DIG_OUTPUT(){
 DISABLE_RE5_PULLUP();
 DISABLE_RE5_OPENDRAIN();
 _TRISE5 = 0;
}
static inline void CONFIG_RE6_AS_DIG_OUTPUT(){
 DISABLE_RE6_PULLUP();
 DISABLE_RE6_OPENDRAIN();
 _TRISE6 = 0;
}
static inline void CONFIG_RE7_AS_DIG_OUTPUT(){
 DISABLE_RE7_PULLUP();
 DISABLE_RE7_OPENDRAIN();
 _TRISE7 = 0;
}
static inline void CONFIG_RF0_AS_DIG_OUTPUT(){
 DISABLE_RF0_PULLUP();
 DISABLE_RF0_OPENDRAIN();
 _TRISF0 = 0;
}
static inline void CONFIG_RF1_AS_DIG_OUTPUT(){
 DISABLE_RF1_PULLUP();
 DISABLE_RF1_OPENDRAIN();
 _TRISF1 = 0;
}
static inline void CONFIG_RF2_AS_DIG_OUTPUT(){
 DISABLE_RF2_PULLUP();
 DISABLE_RF2_OPENDRAIN();
 _TRISF2 = 0;
}
static inline void CONFIG_RF3_AS_DIG_OUTPUT(){
 DISABLE_RF3_PULLUP();
 DISABLE_RF3_OPENDRAIN();
 _TRISF3 = 0;
}
static inline void CONFIG_RF4_AS_DIG_OUTPUT(){
 DISABLE_RF4_PULLUP();
 DISABLE_RF4_OPENDRAIN();
 _TRISF4 = 0;
}
static inline void CONFIG_RF5_AS_DIG_OUTPUT(){
 DISABLE_RF5_PULLUP();
 DISABLE_RF5_OPENDRAIN();
 _TRISF5 = 0;
}
static inline void CONFIG_RF6_AS_DIG_OUTPUT(){
 DISABLE_RF6_PULLUP();
 DISABLE_RF6_OPENDRAIN();
 _TRISF6 = 0;
}
static inline void CONFIG_RG2_AS_DIG_OUTPUT(){
 DISABLE_RG2_PULLUP();
 DISABLE_RG2_OPENDRAIN();
 _TRISG2 = 0;
}
static inline void CONFIG_RG3_AS_DIG_OUTPUT(){
 DISABLE_RG3_PULLUP();
 DISABLE_RG3_OPENDRAIN();
 _TRISG3 = 0;
}
static inline void CONFIG_RG6_AS_DIG_OUTPUT(){
 DISABLE_RG6_PULLUP();
 DISABLE_RG6_OPENDRAIN();
 _TRISG6 = 0;
}
static inline void CONFIG_RG7_AS_DIG_OUTPUT(){
 DISABLE_RG7_PULLUP();
 DISABLE_RG7_OPENDRAIN();
 _TRISG7 = 0;
}
static inline void CONFIG_RG8_AS_DIG_OUTPUT(){
 DISABLE_RG8_PULLUP();
 DISABLE_RG8_OPENDRAIN();
 _TRISG8 = 0;
}
static inline void CONFIG_RG9_AS_DIG_OUTPUT(){
 DISABLE_RG9_PULLUP();
 DISABLE_RG9_OPENDRAIN();
 _TRISG9 = 0;
}
static inline void CONFIG_RB0_AS_DIG_OD_OUTPUT(){
 DISABLE_RB0_PULLUP();
 ENABLE_RB0_OPENDRAIN();
 _TRISB0 = 0;
 _PCFG0 = 1;
}
static inline void CONFIG_RB1_AS_DIG_OD_OUTPUT(){
 DISABLE_RB1_PULLUP();
 ENABLE_RB1_OPENDRAIN();
 _TRISB1 = 0;
 _PCFG1 = 1;
}
static inline void CONFIG_RB2_AS_DIG_OD_OUTPUT(){
 DISABLE_RB2_PULLUP();
 ENABLE_RB2_OPENDRAIN();
 _TRISB2 = 0;
 _PCFG2 = 1;
}
static inline void CONFIG_RB3_AS_DIG_OD_OUTPUT(){
 DISABLE_RB3_PULLUP();
 ENABLE_RB3_OPENDRAIN();
 _TRISB3 = 0;
 _PCFG3 = 1;
}
static inline void CONFIG_RB4_AS_DIG_OD_OUTPUT(){
 DISABLE_RB4_PULLUP();
 ENABLE_RB4_OPENDRAIN();
 _TRISB4 = 0;
 _PCFG4 = 1;
}
static inline void CONFIG_RB5_AS_DIG_OD_OUTPUT(){
 DISABLE_RB5_PULLUP();
 ENABLE_RB5_OPENDRAIN();
 _TRISB5 = 0;
 _PCFG5 = 1;
}
static inline void CONFIG_RB6_AS_DIG_OD_OUTPUT(){
 DISABLE_RB6_PULLUP();
 ENABLE_RB6_OPENDRAIN();
 _TRISB6 = 0;
 _PCFG6 = 1;
}
static inline void CONFIG_RB7_AS_DIG_OD_OUTPUT(){
 DISABLE_RB7_PULLUP();
 ENABLE_RB7_OPENDRAIN();
 _TRISB7 = 0;
 _PCFG7 = 1;
}
static inline void CONFIG_RB8_AS_DIG_OD_OUTPUT(){
 DISABLE_RB8_PULLUP();
 ENABLE_RB8_OPENDRAIN();
 _TRISB8 = 0;
 _PCFG8 = 1;
}
static inline void CONFIG_RB9_AS_DIG_OD_OUTPUT(){
 DISABLE_RB9_PULLUP();
 ENABLE_RB9_OPENDRAIN();
 _TRISB9 = 0;
 _PCFG9 = 1;
}
static inline void CONFIG_RB10_AS_DIG_OD_OUTPUT(){
 DISABLE_RB10_PULLUP();
 ENABLE_RB10_OPENDRAIN();
 _TRISB10 = 0;
 _PCFG10 = 1;
}
static inline void CONFIG_RB11_AS_DIG_OD_OUTPUT(){
 DISABLE_RB11_PULLUP();
 ENABLE_RB11_OPENDRAIN();
 _TRISB11 = 0;
 _PCFG11 = 1;
}
static inline void CONFIG_RB12_AS_DIG_OD_OUTPUT(){
 DISABLE_RB12_PULLUP();
 ENABLE_RB12_OPENDRAIN();
 _TRISB12 = 0;
 _PCFG12 = 1;
}
static inline void CONFIG_RB13_AS_DIG_OD_OUTPUT(){
 DISABLE_RB13_PULLUP();
 ENABLE_RB13_OPENDRAIN();
 _TRISB13 = 0;
 _PCFG13 = 1;
}
static inline void CONFIG_RB14_AS_DIG_OD_OUTPUT(){
 DISABLE_RB14_PULLUP();
 ENABLE_RB14_OPENDRAIN();
 _TRISB14 = 0;
 _PCFG14 = 1;
}
static inline void CONFIG_RB15_AS_DIG_OD_OUTPUT(){
 DISABLE_RB15_PULLUP();
 ENABLE_RB15_OPENDRAIN();
 _TRISB15 = 0;
 _PCFG15 = 1;
}
static inline void CONFIG_RC12_AS_DIG_OD_OUTPUT(){
 DISABLE_RC12_PULLUP();
 ENABLE_RC12_OPENDRAIN();
 _TRISC12 = 0;
}
static inline void CONFIG_RC13_AS_DIG_OD_OUTPUT(){
 DISABLE_RC13_PULLUP();
 ENABLE_RC13_OPENDRAIN();
 _TRISC13 = 0;
}
static inline void CONFIG_RC14_AS_DIG_OD_OUTPUT(){
 DISABLE_RC14_PULLUP();
 ENABLE_RC14_OPENDRAIN();
 _TRISC14 = 0;
}
static inline void CONFIG_RC15_AS_DIG_OD_OUTPUT(){
 DISABLE_RC15_PULLUP();
 ENABLE_RC15_OPENDRAIN();
 _TRISC15 = 0;
}
static inline void CONFIG_RD0_AS_DIG_OD_OUTPUT(){
 DISABLE_RD0_PULLUP();
 ENABLE_RD0_OPENDRAIN();
 _TRISD0 = 0;
}
static inline void CONFIG_RD1_AS_DIG_OD_OUTPUT(){
 DISABLE_RD1_PULLUP();
 ENABLE_RD1_OPENDRAIN();
 _TRISD1 = 0;
}
static inline void CONFIG_RD2_AS_DIG_OD_OUTPUT(){
 DISABLE_RD2_PULLUP();
 ENABLE_RD2_OPENDRAIN();
 _TRISD2 = 0;
}
static inline void CONFIG_RD3_AS_DIG_OD_OUTPUT(){
 DISABLE_RD3_PULLUP();
 ENABLE_RD3_OPENDRAIN();
 _TRISD3 = 0;
}
static inline void CONFIG_RD4_AS_DIG_OD_OUTPUT(){
 DISABLE_RD4_PULLUP();
 ENABLE_RD4_OPENDRAIN();
 _TRISD4 = 0;
}
static inline void CONFIG_RD5_AS_DIG_OD_OUTPUT(){
 DISABLE_RD5_PULLUP();
 ENABLE_RD5_OPENDRAIN();
 _TRISD5 = 0;
}
static inline void CONFIG_RD6_AS_DIG_OD_OUTPUT(){
 DISABLE_RD6_PULLUP();
 ENABLE_RD6_OPENDRAIN();
 _TRISD6 = 0;
}
static inline void CONFIG_RD7_AS_DIG_OD_OUTPUT(){
 DISABLE_RD7_PULLUP();
 ENABLE_RD7_OPENDRAIN();
 _TRISD7 = 0;
}
static inline void CONFIG_RD8_AS_DIG_OD_OUTPUT(){
 DISABLE_RD8_PULLUP();
 ENABLE_RD8_OPENDRAIN();
 _TRISD8 = 0;
}
static inline void CONFIG_RD9_AS_DIG_OD_OUTPUT(){
 DISABLE_RD9_PULLUP();
 ENABLE_RD9_OPENDRAIN();
 _TRISD9 = 0;
}
static inline void CONFIG_RD10_AS_DIG_OD_OUTPUT(){
 DISABLE_RD10_PULLUP();
 ENABLE_RD10_OPENDRAIN();
 _TRISD10 = 0;
}
static inline void CONFIG_RD11_AS_DIG_OD_OUTPUT(){
 DISABLE_RD11_PULLUP();
 ENABLE_RD11_OPENDRAIN();
 _TRISD11 = 0;
}
static inline void CONFIG_RE0_AS_DIG_OD_OUTPUT(){
 DISABLE_RE0_PULLUP();
 ENABLE_RE0_OPENDRAIN();
 _TRISE0 = 0;
}
static inline void CONFIG_RE1_AS_DIG_OD_OUTPUT(){
 DISABLE_RE1_PULLUP();
 ENABLE_RE1_OPENDRAIN();
 _TRISE1 = 0;
}
static inline void CONFIG_RE2_AS_DIG_OD_OUTPUT(){
 DISABLE_RE2_PULLUP();
 ENABLE_RE2_OPENDRAIN();
 _TRISE2 = 0;
}
static inline void CONFIG_RE3_AS_DIG_OD_OUTPUT(){
 DISABLE_RE3_PULLUP();
 ENABLE_RE3_OPENDRAIN();
 _TRISE3 = 0;
}
static inline void CONFIG_RE4_AS_DIG_OD_OUTPUT(){
 DISABLE_RE4_PULLUP();
 ENABLE_RE4_OPENDRAIN();
 _TRISE4 = 0;
}
static inline void CONFIG_RE5_AS_DIG_OD_OUTPUT(){
 DISABLE_RE5_PULLUP();
 ENABLE_RE5_OPENDRAIN();
 _TRISE5 = 0;
}
static inline void CONFIG_RE6_AS_DIG_OD_OUTPUT(){
 DISABLE_RE6_PULLUP();
 ENABLE_RE6_OPENDRAIN();
 _TRISE6 = 0;
}
static inline void CONFIG_RE7_AS_DIG_OD_OUTPUT(){
 DISABLE_RE7_PULLUP();
 ENABLE_RE7_OPENDRAIN();
 _TRISE7 = 0;
}
static inline void CONFIG_RF0_AS_DIG_OD_OUTPUT(){
 DISABLE_RF0_PULLUP();
 ENABLE_RF0_OPENDRAIN();
 _TRISF0 = 0;
}
static inline void CONFIG_RF1_AS_DIG_OD_OUTPUT(){
 DISABLE_RF1_PULLUP();
 ENABLE_RF1_OPENDRAIN();
 _TRISF1 = 0;
}
static inline void CONFIG_RF2_AS_DIG_OD_OUTPUT(){
 DISABLE_RF2_PULLUP();
 ENABLE_RF2_OPENDRAIN();
 _TRISF2 = 0;
}
static inline void CONFIG_RF3_AS_DIG_OD_OUTPUT(){
 DISABLE_RF3_PULLUP();
 ENABLE_RF3_OPENDRAIN();
 _TRISF3 = 0;
}
static inline void CONFIG_RF4_AS_DIG_OD_OUTPUT(){
 DISABLE_RF4_PULLUP();
 ENABLE_RF4_OPENDRAIN();
 _TRISF4 = 0;
}
static inline void CONFIG_RF5_AS_DIG_OD_OUTPUT(){
 DISABLE_RF5_PULLUP();
 ENABLE_RF5_OPENDRAIN();
 _TRISF5 = 0;
}
static inline void CONFIG_RF6_AS_DIG_OD_OUTPUT(){
 DISABLE_RF6_PULLUP();
 ENABLE_RF6_OPENDRAIN();
 _TRISF6 = 0;
}
static inline void CONFIG_RG2_AS_DIG_OD_OUTPUT(){
 DISABLE_RG2_PULLUP();
 ENABLE_RG2_OPENDRAIN();
 _TRISG2 = 0;
}
static inline void CONFIG_RG3_AS_DIG_OD_OUTPUT(){
 DISABLE_RG3_PULLUP();
 ENABLE_RG3_OPENDRAIN();
 _TRISG3 = 0;
}
static inline void CONFIG_RG6_AS_DIG_OD_OUTPUT(){
 DISABLE_RG6_PULLUP();
 ENABLE_RG6_OPENDRAIN();
 _TRISG6 = 0;
}
static inline void CONFIG_RG7_AS_DIG_OD_OUTPUT(){
 DISABLE_RG7_PULLUP();
 ENABLE_RG7_OPENDRAIN();
 _TRISG7 = 0;
}
static inline void CONFIG_RG8_AS_DIG_OD_OUTPUT(){
 DISABLE_RG8_PULLUP();
 ENABLE_RG8_OPENDRAIN();
 _TRISG8 = 0;
}
static inline void CONFIG_RG9_AS_DIG_OD_OUTPUT(){
 DISABLE_RG9_PULLUP();
 ENABLE_RG9_OPENDRAIN();
 _TRISG9 = 0;
}
static inline void CONFIG_RB0_AS_DIG_INPUT(){
 DISABLE_RB0_PULLUP();
 _TRISB0 = 1;
 _PCFG0 = 1;
}
static inline void CONFIG_RB1_AS_DIG_INPUT(){
 DISABLE_RB1_PULLUP();
 _TRISB1 = 1;
 _PCFG1 = 1;
}
static inline void CONFIG_RB2_AS_DIG_INPUT(){
 DISABLE_RB2_PULLUP();
 _TRISB2 = 1;
 _PCFG2 = 1;
}
static inline void CONFIG_RB3_AS_DIG_INPUT(){
 DISABLE_RB3_PULLUP();
 _TRISB3 = 1;
 _PCFG3 = 1;
}
static inline void CONFIG_RB4_AS_DIG_INPUT(){
 DISABLE_RB4_PULLUP();
 _TRISB4 = 1;
 _PCFG4 = 1;
}
static inline void CONFIG_RB5_AS_DIG_INPUT(){
 DISABLE_RB5_PULLUP();
 _TRISB5 = 1;
 _PCFG5 = 1;
}
static inline void CONFIG_RB6_AS_DIG_INPUT(){
 DISABLE_RB6_PULLUP();
 _TRISB6 = 1;
 _PCFG6 = 1;
}
static inline void CONFIG_RB7_AS_DIG_INPUT(){
 DISABLE_RB7_PULLUP();
 _TRISB7 = 1;
 _PCFG7 = 1;
}
static inline void CONFIG_RB8_AS_DIG_INPUT(){
 DISABLE_RB8_PULLUP();
 _TRISB8 = 1;
 _PCFG8 = 1;
}
static inline void CONFIG_RB9_AS_DIG_INPUT(){
 DISABLE_RB9_PULLUP();
 _TRISB9 = 1;
 _PCFG9 = 1;
}
static inline void CONFIG_RB10_AS_DIG_INPUT(){
 DISABLE_RB10_PULLUP();
 _TRISB10 = 1;
 _PCFG10 = 1;
}
static inline void CONFIG_RB11_AS_DIG_INPUT(){
 DISABLE_RB11_PULLUP();
 _TRISB11 = 1;
 _PCFG11 = 1;
}
static inline void CONFIG_RB12_AS_DIG_INPUT(){
 DISABLE_RB12_PULLUP();
 _TRISB12 = 1;
 _PCFG12 = 1;
}
static inline void CONFIG_RB13_AS_DIG_INPUT(){
 DISABLE_RB13_PULLUP();
 _TRISB13 = 1;
 _PCFG13 = 1;
}
static inline void CONFIG_RB14_AS_DIG_INPUT(){
 DISABLE_RB14_PULLUP();
 _TRISB14 = 1;
 _PCFG14 = 1;
}
static inline void CONFIG_RB15_AS_DIG_INPUT(){
 DISABLE_RB15_PULLUP();
 _TRISB15 = 1;
 _PCFG15 = 1;
}
static inline void CONFIG_RC12_AS_DIG_INPUT(){
 DISABLE_RC12_PULLUP();
 _TRISC12 = 1;
}
static inline void CONFIG_RC13_AS_DIG_INPUT(){
 DISABLE_RC13_PULLUP();
 _TRISC13 = 1;
}
static inline void CONFIG_RC14_AS_DIG_INPUT(){
 DISABLE_RC14_PULLUP();
 _TRISC14 = 1;
}
static inline void CONFIG_RC15_AS_DIG_INPUT(){
 DISABLE_RC15_PULLUP();
 _TRISC15 = 1;
}
static inline void CONFIG_RD0_AS_DIG_INPUT(){
 DISABLE_RD0_PULLUP();
 _TRISD0 = 1;
}
static inline void CONFIG_RD1_AS_DIG_INPUT(){
 DISABLE_RD1_PULLUP();
 _TRISD1 = 1;
}
static inline void CONFIG_RD2_AS_DIG_INPUT(){
 DISABLE_RD2_PULLUP();
 _TRISD2 = 1;
}
static inline void CONFIG_RD3_AS_DIG_INPUT(){
 DISABLE_RD3_PULLUP();
 _TRISD3 = 1;
}
static inline void CONFIG_RD4_AS_DIG_INPUT(){
 DISABLE_RD4_PULLUP();
 _TRISD4 = 1;
}
static inline void CONFIG_RD5_AS_DIG_INPUT(){
 DISABLE_RD5_PULLUP();
 _TRISD5 = 1;
}
static inline void CONFIG_RD6_AS_DIG_INPUT(){
 DISABLE_RD6_PULLUP();
 _TRISD6 = 1;
}
static inline void CONFIG_RD7_AS_DIG_INPUT(){
 DISABLE_RD7_PULLUP();
 _TRISD7 = 1;
}
static inline void CONFIG_RD8_AS_DIG_INPUT(){
 DISABLE_RD8_PULLUP();
 _TRISD8 = 1;
}
static inline void CONFIG_RD9_AS_DIG_INPUT(){
 DISABLE_RD9_PULLUP();
 _TRISD9 = 1;
}
static inline void CONFIG_RD10_AS_DIG_INPUT(){
 DISABLE_RD10_PULLUP();
 _TRISD10 = 1;
}
static inline void CONFIG_RD11_AS_DIG_INPUT(){
 DISABLE_RD11_PULLUP();
 _TRISD11 = 1;
}
static inline void CONFIG_RE0_AS_DIG_INPUT(){
 DISABLE_RE0_PULLUP();
 _TRISE0 = 1;
}
static inline void CONFIG_RE1_AS_DIG_INPUT(){
 DISABLE_RE1_PULLUP();
 _TRISE1 = 1;
}
static inline void CONFIG_RE2_AS_DIG_INPUT(){
 DISABLE_RE2_PULLUP();
 _TRISE2 = 1;
}
static inline void CONFIG_RE3_AS_DIG_INPUT(){
 DISABLE_RE3_PULLUP();
 _TRISE3 = 1;
}
static inline void CONFIG_RE4_AS_DIG_INPUT(){
 DISABLE_RE4_PULLUP();
 _TRISE4 = 1;
}
static inline void CONFIG_RE5_AS_DIG_INPUT(){
 DISABLE_RE5_PULLUP();
 _TRISE5 = 1;
}
static inline void CONFIG_RE6_AS_DIG_INPUT(){
 DISABLE_RE6_PULLUP();
 _TRISE6 = 1;
}
static inline void CONFIG_RE7_AS_DIG_INPUT(){
 DISABLE_RE7_PULLUP();
 _TRISE7 = 1;
}
static inline void CONFIG_RF0_AS_DIG_INPUT(){
 DISABLE_RF0_PULLUP();
 _TRISF0 = 1;
}
static inline void CONFIG_RF1_AS_DIG_INPUT(){
 DISABLE_RF1_PULLUP();
 _TRISF1 = 1;
}
static inline void CONFIG_RF2_AS_DIG_INPUT(){
 DISABLE_RF2_PULLUP();
 _TRISF2 = 1;
}
static inline void CONFIG_RF3_AS_DIG_INPUT(){
 DISABLE_RF3_PULLUP();
 _TRISF3 = 1;
}
static inline void CONFIG_RF4_AS_DIG_INPUT(){
 DISABLE_RF4_PULLUP();
 _TRISF4 = 1;
}
static inline void CONFIG_RF5_AS_DIG_INPUT(){
 DISABLE_RF5_PULLUP();
 _TRISF5 = 1;
}
static inline void CONFIG_RF6_AS_DIG_INPUT(){
 DISABLE_RF6_PULLUP();
 _TRISF6 = 1;
}
static inline void CONFIG_RG2_AS_DIG_INPUT(){
 DISABLE_RG2_PULLUP();
 _TRISG2 = 1;
}
static inline void CONFIG_RG3_AS_DIG_INPUT(){
 DISABLE_RG3_PULLUP();
 _TRISG3 = 1;
}
static inline void CONFIG_RG6_AS_DIG_INPUT(){
 DISABLE_RG6_PULLUP();
 _TRISG6 = 1;
}
static inline void CONFIG_RG7_AS_DIG_INPUT(){
 DISABLE_RG7_PULLUP();
 _TRISG7 = 1;
}
static inline void CONFIG_RG8_AS_DIG_INPUT(){
 DISABLE_RG8_PULLUP();
 _TRISG8 = 1;
}
static inline void CONFIG_RG9_AS_DIG_INPUT(){
 DISABLE_RG9_PULLUP();
 _TRISG9 = 1;
}
#define CONFIG_RP0_AS_DIG_PIN()  _PCFG0 = 1
#define CONFIG_RP1_AS_DIG_PIN()  _PCFG1 = 1
#define CONFIG_RP2_AS_DIG_PIN() 
#define CONFIG_RP3_AS_DIG_PIN() 
#define CONFIG_RP4_AS_DIG_PIN() 
#define CONFIG_RP5_AS_DIG_PIN() 
#define CONFIG_RP6_AS_DIG_PIN()  _PCFG6 = 1
#define CONFIG_RP7_AS_DIG_PIN()  _PCFG7 = 1
#define CONFIG_RP8_AS_DIG_PIN()  _PCFG8 = 1
#define CONFIG_RP9_AS_DIG_PIN()  _PCFG9 = 1
#define CONFIG_RP10_AS_DIG_PIN() 
#define CONFIG_RP11_AS_DIG_PIN() 
#define CONFIG_RP12_AS_DIG_PIN() 
#define CONFIG_RP13_AS_DIG_PIN()  _PCFG2 = 1
#define CONFIG_RP14_AS_DIG_PIN()  _PCFG14 = 1
#define CONFIG_RP15_AS_DIG_PIN() 
#define CONFIG_RP16_AS_DIG_PIN() 
#define CONFIG_RP17_AS_DIG_PIN() 
#define CONFIG_RP18_AS_DIG_PIN()  _PCFG5 = 1
#define CONFIG_RP19_AS_DIG_PIN() 
#define CONFIG_RP20_AS_DIG_PIN() 
#define CONFIG_RP21_AS_DIG_PIN() 
#define CONFIG_RP22_AS_DIG_PIN() 
#define CONFIG_RP23_AS_DIG_PIN() 
#define CONFIG_RP24_AS_DIG_PIN() 
#define CONFIG_RP25_AS_DIG_PIN() 
#define CONFIG_RP26_AS_DIG_PIN() 
#define CONFIG_RP27_AS_DIG_PIN() 
#define CONFIG_RP28_AS_DIG_PIN()  _PCFG4 = 1
#define CONFIG_RP29_AS_DIG_PIN()  _PCFG15 = 1
#define CONFIG_RP30_AS_DIG_PIN() 
#define CONFIG_RP31_AS_DIG_PIN() 
#define CONFIG_RP32_AS_DIG_PIN() 
#define CONFIG_RP33_AS_DIG_PIN() 
#define CONFIG_RP34_AS_DIG_PIN() 
#define CONFIG_RP35_AS_DIG_PIN() 
#define CONFIG_RP36_AS_DIG_PIN() 
#define CONFIG_RP37_AS_DIG_PIN() 
#define CONFIG_RP38_AS_DIG_PIN() 
#define CONFIG_RP39_AS_DIG_PIN() 
#define CONFIG_RP40_AS_DIG_PIN() 
#define CONFIG_RP41_AS_DIG_PIN() 
#define CONFIG_RP42_AS_DIG_PIN() 
#define CONFIG_RP43_AS_DIG_PIN() 
#define CONFIG_RP44_AS_DIG_PIN() 
#define CONFIG_RP45_AS_DIG_PIN() 
#ifdef _PCFG0
static inline void CONFIG_AN0_AS_ANALOG(){
  CONFIG_RB0_AS_DIG_INPUT();
  _PCFG0 = 0;
}
static inline void CONFIG_AN0_AS_DIGITAL(){
  _PCFG0 = 1;
}
#endif
#ifdef _PCFG1
static inline void CONFIG_AN1_AS_ANALOG(){
  CONFIG_RB1_AS_DIG_INPUT();
  _PCFG1 = 0;
}
static inline void CONFIG_AN1_AS_DIGITAL(){
  _PCFG1 = 1;
}
#endif
#ifdef _PCFG2
static inline void CONFIG_AN2_AS_ANALOG(){
  CONFIG_RB2_AS_DIG_INPUT();
  _PCFG2 = 0;
}
static inline void CONFIG_AN2_AS_DIGITAL(){
  _PCFG2 = 1;
}
#endif
#ifdef _PCFG3
static inline void CONFIG_AN3_AS_ANALOG(){
  CONFIG_RB3_AS_DIG_INPUT();
  _PCFG3 = 0;
}
static inline void CONFIG_AN3_AS_DIGITAL(){
  _PCFG3 = 1;
}
#endif
#ifdef _PCFG4
static inline void CONFIG_AN4_AS_ANALOG(){
  CONFIG_RB4_AS_DIG_INPUT();
  _PCFG4 = 0;
}
static inline void CONFIG_AN4_AS_DIGITAL(){
  _PCFG4 = 1;
}
#endif
#ifdef _PCFG5
static inline void CONFIG_AN5_AS_ANALOG(){
  CONFIG_RB5_AS_DIG_INPUT();
  _PCFG5 = 0;
}
static inline void CONFIG_AN5_AS_DIGITAL(){
  _PCFG5 = 1;
}
#endif
#ifdef _PCFG6
static inline void CONFIG_AN6_AS_ANALOG(){
  CONFIG_RB6_AS_DIG_INPUT();
  _PCFG6 = 0;
}
static inline void CONFIG_AN6_AS_DIGITAL(){
  _PCFG6 = 1;
}
#endif
#ifdef _PCFG7
static inline void CONFIG_AN7_AS_ANALOG(){
  CONFIG_RB7_AS_DIG_INPUT();
  _PCFG7 = 0;
}
static inline void CONFIG_AN7_AS_DIGITAL(){
  _PCFG7 = 1;
}
#endif
#ifdef _PCFG8
static inline void CONFIG_AN8_AS_ANALOG(){
  CONFIG_RB8_AS_DIG_INPUT();
  _PCFG8 = 0;
}
static inline void CONFIG_AN8_AS_DIGITAL(){
  _PCFG8 = 1;
}
#endif
#ifdef _PCFG9
static inline void CONFIG_AN9_AS_ANALOG(){
  CONFIG_RB9_AS_DIG_INPUT();
  _PCFG9 = 0;
}
static inline void CONFIG_AN9_AS_DIGITAL(){
  _PCFG9 = 1;
}
#endif
#ifdef _PCFG10
static inline void CONFIG_AN10_AS_ANALOG(){
  CONFIG_RB10_AS_DIG_INPUT();
  _PCFG10 = 0;
}
static inline void CONFIG_AN10_AS_DIGITAL(){
  _PCFG10 = 1;
}
#endif
#ifdef _PCFG11
static inline void CONFIG_AN11_AS_ANALOG(){
  CONFIG_RB11_AS_DIG_INPUT();
  _PCFG11 = 0;
}
static inline void CONFIG_AN11_AS_DIGITAL(){
  _PCFG11 = 1;
}
#endif
#ifdef _PCFG12
static inline void CONFIG_AN12_AS_ANALOG(){
  CONFIG_RB12_AS_DIG_INPUT();
  _PCFG12 = 0;
}
static inline void CONFIG_AN12_AS_DIGITAL(){
  _PCFG12 = 1;
}
#endif
#ifdef _PCFG13
static inline void CONFIG_AN13_AS_ANALOG(){
  CONFIG_RB13_AS_DIG_INPUT();
  _PCFG13 = 0;
}
static inline void CONFIG_AN13_AS_DIGITAL(){
  _PCFG13 = 1;
}
#endif
#ifdef _PCFG14
static inline void CONFIG_AN14_AS_ANALOG(){
  CONFIG_RB14_AS_DIG_INPUT();
  _PCFG14 = 0;
}
static inline void CONFIG_AN14_AS_DIGITAL(){
  _PCFG14 = 1;
}
#endif
#ifdef _PCFG15
static inline void CONFIG_AN15_AS_ANALOG(){
  CONFIG_RB15_AS_DIG_INPUT();
  _PCFG15 = 0;
}
static inline void CONFIG_AN15_AS_DIGITAL(){
  _PCFG15 = 1;
}
#endif
#ifdef _PCFG16
static inline void CONFIG_AN16_AS_ANALOG(){
  _PCFG16 = 0;
}
static inline void CONFIG_AN16_AS_DIGITAL(){
  _PCFG16 = 1;
}
#endif
#ifdef _PCFG17
static inline void CONFIG_AN17_AS_ANALOG(){
  _PCFG17 = 0;
}
static inline void CONFIG_AN17_AS_DIGITAL(){
  _PCFG17 = 1;
}
#endif
#ifdef _PCFG18
static inline void CONFIG_AN18_AS_ANALOG(){
  _PCFG18 = 0;
}
static inline void CONFIG_AN18_AS_DIGITAL(){
  _PCFG18 = 1;
}
#endif
#ifdef _PCFG19
static inline void CONFIG_AN19_AS_ANALOG(){
  _PCFG19 = 0;
}
static inline void CONFIG_AN19_AS_DIGITAL(){
  _PCFG19 = 1;
}
#endif
#ifdef _PCFG20
static inline void CONFIG_AN20_AS_ANALOG(){
  _PCFG20 = 0;
}
static inline void CONFIG_AN20_AS_DIGITAL(){
  _PCFG20 = 1;
}
#endif
#ifdef _PCFG21
static inline void CONFIG_AN21_AS_ANALOG(){
  _PCFG21 = 0;
}
static inline void CONFIG_AN21_AS_DIGITAL(){
  _PCFG21 = 1;
}
#endif
#ifdef _PCFG22
static inline void CONFIG_AN22_AS_ANALOG(){
  _PCFG22 = 0;
}
static inline void CONFIG_AN22_AS_DIGITAL(){
  _PCFG22 = 1;
}
#endif
#ifdef _PCFG23
static inline void CONFIG_AN23_AS_ANALOG(){
  _PCFG23 = 0;
}
static inline void CONFIG_AN23_AS_DIGITAL(){
  _PCFG23 = 1;
}
#endif
#ifdef _PCFG24
static inline void CONFIG_AN24_AS_ANALOG(){
  _PCFG24 = 0;
}
static inline void CONFIG_AN24_AS_DIGITAL(){
  _PCFG24 = 1;
}
#endif
#ifdef _PCFG25
static inline void CONFIG_AN25_AS_ANALOG(){
  _PCFG25 = 0;
}
static inline void CONFIG_AN25_AS_DIGITAL(){
  _PCFG25 = 1;
}
#endif
#ifdef _PCFG26
static inline void CONFIG_AN26_AS_ANALOG(){
  _PCFG26 = 0;
}
static inline void CONFIG_AN26_AS_DIGITAL(){
  _PCFG26 = 1;
}
#endif
#ifdef _PCFG27
static inline void CONFIG_AN27_AS_ANALOG(){
  _PCFG27 = 0;
}
static inline void CONFIG_AN27_AS_DIGITAL(){
  _PCFG27 = 1;
}
#endif
#ifdef _PCFG28
static inline void CONFIG_AN28_AS_ANALOG(){
  _PCFG28 = 0;
}
static inline void CONFIG_AN28_AS_DIGITAL(){
  _PCFG28 = 1;
}
#endif
#ifdef _PCFG29
static inline void CONFIG_AN29_AS_ANALOG(){
  _PCFG29 = 0;
}
static inline void CONFIG_AN29_AS_DIGITAL(){
  _PCFG29 = 1;
}
#endif
#ifdef _PCFG30
static inline void CONFIG_AN30_AS_ANALOG(){
  _PCFG30 = 0;
}
static inline void CONFIG_AN30_AS_DIGITAL(){
  _PCFG30 = 1;
}
#endif
#ifdef _PCFG31
static inline void CONFIG_AN31_AS_ANALOG(){
  _PCFG31 = 0;
}
static inline void CONFIG_AN31_AS_DIGITAL(){
  _PCFG31 = 1;
}
#endif
#define DISABLE_C2IND_ANALOG()   
#define DISABLE_U2CTS_ANALOG()   
#define DISABLE_CTPLS_ANALOG()   
#define DISABLE_U4TX_ANALOG()   
#define DISABLE_SS2_ANALOG()   
#define DISABLE_U3TX_ANALOG()   
#define DISABLE_C1OUT_ANALOG()   
#define DISABLE_INT1_ANALOG()   
#define DISABLE_U1RTS_ANALOG()   
#define DISABLE_T5CK_ANALOG()   
#define DISABLE_C1IND_ANALOG()   
#define DISABLE_U3CTS_ANALOG()   
#define DISABLE_OC5_ANALOG()   
#define DISABLE_U2TX_ANALOG()   
#define DISABLE_C2INA_ANALOG()   
#define DISABLE_INT0_ANALOG()   
#define DISABLE_U1BCLK_ANALOG()   
#define DISABLE_SS1_ANALOG()   
#define DISABLE_IC4_ANALOG()   
#define DISABLE_OCFB_ANALOG()   
#define DISABLE_C1TX_ANALOG()   
#define DISABLE_RTCC_ANALOG()   
#define DISABLE_IC3_ANALOG()   
#define DISABLE_T3CK_ANALOG()   
#define DISABLE_C2OUT_ANALOG()   
#define DISABLE_INT2_ANALOG()   
#define DISABLE_OCFA_ANALOG()   
#define DISABLE_OC4_ANALOG()   
#define DISABLE_U1RX_ANALOG()   
#define DISABLE_IC8_ANALOG()   
#define DISABLE_U3RX_ANALOG()   
#define DISABLE_CTED2_ANALOG()   
#define DISABLE_IC1_ANALOG()   
#define DISABLE_U2BCLK_ANALOG()   
#define DISABLE_C1INA_ANALOG()   
#define DISABLE_T4CK_ANALOG()   
#define DISABLE_C2INC_ANALOG()   
#define DISABLE_IC7_ANALOG()   
#define DISABLE_IC2_ANALOG()   
#define DISABLE_U2RTS_ANALOG()   
#define DISABLE_U4RTS_ANALOG()   
#define DISABLE_SDI2_ANALOG()   
#define DISABLE_OC2_ANALOG()   
#define DISABLE_C1RX_ANALOG()   
#define DISABLE_C2RX_ANALOG()   
#define DISABLE_SDO1_ANALOG()   
#define DISABLE_U1CTS_ANALOG()   
#define DISABLE_OC3_ANALOG()   
#define DISABLE_C21INB_ANALOG()   
#define DISABLE_U1TX_ANALOG()   
#define DISABLE_T1CK_ANALOG()   
#define DISABLE_SCK1_ANALOG()   
#define DISABLE_U2RX_ANALOG()   
#define DISABLE_T2CK_ANALOG()   
#define DISABLE_CTED1_ANALOG()   
#define DISABLE_U3RTS_ANALOG()   
#define DISABLE_SDO2_ANALOG()   
#define DISABLE_C1INC_ANALOG()   
#define DISABLE_U4RX_ANALOG()   
#define DISABLE_IC5_ANALOG()   
#define DISABLE_SDI1_ANALOG()   
#define DISABLE_C1INB_ANALOG()   
#define DISABLE_OC1_ANALOG()   
#define DISABLE_SCK2_ANALOG()   
#define DISABLE_IC6_ANALOG()   
#define DISABLE_U4CTS_ANALOG()   
#define _PIC24_DIGIO_DEFINED
